import testImg from '@/assets/testImg.jpg'

export const EmployeeFundsData = [
    {
        picture: testImg,
        employeeName: 'Justin Lipshutz',
        Department: 'Marketing',
        Hours: '22',
        TotalMonthFund: '$400',
        Productivity: '100%',
        type: 'increase',
    },
    {
        picture: testImg,
        employeeName: 'Justin Lipshutz',
        Department: 'Finance',
        Hours: '22',
        TotalMonthFund: '$400',
        Productivity: '100%',
        type: 'decrease',
    },
    {
        picture: testImg,
        employeeName: 'Justin Lipshutz',
        Department: 'R&D',
        Hours: '22',
        TotalMonthFund: '$400',
        Productivity: '100%',
        type: 'increase',
    },
    {
        picture: testImg,
        employeeName: 'Justin Lipshutz',
        Department: 'R&D',
        Hours: '22',
        TotalMonthFund: '$400',
        Productivity: '100%',
        type: 'decrease',
    },
    {
        picture: testImg,
        employeeName: 'Justin Lipshutz',
        Department: 'Finance',
        Hours: '22',
        TotalMonthFund: '$400',
        Productivity: '100%',
        type: 'decrease',
    },
    {
        picture: testImg,
        employeeName: 'Justin Lipshutz',
        Department: 'R&D',
        Hours: '22',
        TotalMonthFund: '$400',
        Productivity: '100%',
        type: 'decrease',
    },
]